### ISSUE TITLE
[Issue]: Is there any instruction or vedio which can help users develop step by step

### ISSUE THREAD

**Issue by sharecreators-kevin** [Voltstro-Studios/UnityWebBrowser#100]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Git Repo

### What Unity version are you running?

2021.3.6f1c1

### Describe what the issue you are experiencing is.

I installed UWB, but I dont know how to get it work. Is there any instruction or vedio which can help users develop step by step?

The first issue I came accross:
<img width="961" alt="企业微信截图_16590894211601" src="https://user-images.githubusercontent.com/104351526/182059338-c692d165-a439-4f3a-860a-7ca7a1d6e8f1.png">

What shoud I type in this input field of browser engine?

<img width="739" alt="企业微信截图_16590904588011" src="https://user-images.githubusercontent.com/104351526/182059461-2764daf5-dc54-46b5-8ccb-63044f02e399.png">
This is the error if the field is blank.

### Provide reproducible steps for this issue.

It can be reproduced.

**Comment by Voltstro** [comment]
Your Unity inspector is set to debug mode, which is hiding the custom inspector for the browser engine option.

If you need a sample, there is one included in the package, you just need to import it using the package manager.

**Comment by kaihekaihe** [comment]
Could you help to give a screenshot where the example is？I cant find it.
This is the code structure:
<img width="298" alt="企业微信截图_16593430489164" src="https://user-images.githubusercontent.com/52127183/182148437-a989d1e0-9227-4a4e-bc64-1018e840c3a0.png">

**Comment by kaihekaihe** [comment]
![image](https://user-images.githubusercontent.com/52127183/182279750-3e2397f5-0219-40e5-9b80-9b07af48a729.png)

I have imported samples and how can I run the sample to see webpage

**Comment by Voltstro** [comment]
Its a prefab. Just add the prefab to your scene.

**Comment by kaihekaihe** [comment]
![image](https://user-images.githubusercontent.com/52127183/182305741-57e3c373-0998-475c-b25f-d03834a73ddb.png)

Yes It works.

I want to  spawn a browser window by add code after line 11, Is there examples?
![image](https://user-images.githubusercontent.com/52127183/182306774-72ad302e-390e-4101-a0b7-dbbdd4885023.png)

**Comment by Voltstro** [comment]
Are you saying display a web page in an editor window?

1. No UWB doesn't support doing that
2. Thats beyond what this issue was originally about

**Comment by Voltstro** [comment]
Closing this now as the orginal issue seems to be resolved now and no other comments were made.
