### ISSUE TITLE
Error when opening project

### ISSUE THREAD

**Issue by viettham1998** [Voltstro-Studios/UnityWebBrowser#12]
I followed your instructions but when I open the unity project there are few errors
![image](https://user-images.githubusercontent.com/44217470/122406683-3aee8700-cfab-11eb-89b0-9057600f1398.png)

**Comment by Voltstro** [comment]
Try opening the solution at `src/UnityWebBrowser.sln`, and build the UnityWebBrowser.Shared project with `ReleaseUnity | Any CPU` set as the configuration.
It should then copy its Dll to `src/Packages/UnityWebBrowser/Plugins/UnityWebBrowser.Shared.dll`, but just double check that its there. If its not just manually copy it.
Also make sure Unity is closed when you do this.

**Comment by viettham1998** [comment]
oh, I fixed it, thank you so much
