### ISSUE TITLE
[Issue]: how js calls the C# method

### ISSUE THREAD

**Issue by N3GIS** [Voltstro-Studios/UnityWebBrowser#120]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Git Repo

### What Unity version are you running?

2021.3.5f1

### Describe what the issue you are experiencing is.

how js calls the C# method？Can you provide examples of js interacting with C#?

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

**Comment by Voltstro** [comment]
#81 Thats not supported yet.

**Comment by Voltstro** [comment]
Closing. Is duplicate and feature request.
