### ISSUE TITLE
[Issue] UWB Not Starting

### ISSUE THREAD

**Issue by NykytaP** [Voltstro-Studios/UnityWebBrowser#153]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.17f1

### Describe what the issue you are experiencing is.

After setup and using example you provide i always get the same trouble: uwb shutdown. 
Screen below
![Screenshot_1](https://user-images.githubusercontent.com/55349470/220208576-2af7630c-7ae3-4c65-ba62-231c5442d898.png)

### Provide reproducible steps for this issue.

1. Install plugins from list in docs
2. Drop example prefab on scene
3. Run

**Comment by Voltstro** [comment]
I've just setup a new project in Unity 2021.3.19f1 on Windows, followed the UWB docs and experienced no issues.

I need more info that what you have provided, are there any other logs? Are you sure you have installed all the required packages (Core, Engine, Engine Natives)?

**Comment by Voltstro** [comment]
If someone could provide a re-producible project with this issue that would be great. I've still yet to been able to re-produce this.

CC: @fmatulic

**Comment by LGuilhermeRodrigues** [comment]
I have also faced this issue. That was my first project and enrything was running ok before.

I saw that there was this message before the error, It was loading some stuff and I decided to delete the Library folder.

```
[Web Browser]: Process Path: 'C:\Users\guilherme\Voltstro WebBrowser\Library\PackageCache\dev.voltstro.unitywebbrowser.engine.cef.win.x64@2.0.1-106.1.1\Engine~\UnityWebBrowser.Engine.Cef.exe'
Working: 'C:\Users\guilherme\Voltstro WebBrowser\Library\PackageCache\dev.voltstro.unitywebbrowser.engine.cef.win.x64@2.0.1-106.1.1\Engine~\'
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Helper.WebBrowserUtils:CreateEngineProcess (VoltstroStudios.UnityWebBrowser.Logging.IWebBrowserLogger,VoltstroStudios.UnityWebBrowser.Core.Engines.Engine,string,System.Diagnostics.DataReceivedEventHandler,System.Diagnostics.DataReceivedEventHandler) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Helper/WebBrowserUtils.cs:165)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:StartEngineProcess (string) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Core/WebBrowserClient.cs:389)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<>c__DisplayClass55_0:<Init>b__0 () (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Core/WebBrowserClient.cs:377)
Cysharp.Threading.Tasks.UniTask:Create (System.Func`1<Cysharp.Threading.Tasks.UniTask>) (at Library/PackageCache/com.cysharp.unitask@2.3.3/Runtime/UniTask.Factory.cs:81)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:Init () (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Core/WebBrowserClient.cs:376)
VoltstroStudios.UnityWebBrowser.Core.BaseUwbClientManager:Start () (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.1/Runtime/Core/BaseUwbClientManager.cs:32)
```

I couldn't delete some stuff because it was being used even after I closed everything. So I had to stop some process.

![image](https://user-images.githubusercontent.com/68308462/226213014-e34314fd-61ac-4bb9-84e3-8bee558cc788.png)

Now it's working again 😄

**Comment by LGuilhermeRodrigues** [comment]
Just stopping the browser process is enough, we don't need to delete the Library folder

**Comment by shubhamnegi1234** [comment]
can we have some solution like auto cleanup or stopping browser process to make it run non stop ?

**Comment by Voltstro** [comment]
I am consolidating everything related to this issue into #166. Please see that issue report.
