### ISSUE TITLE
[Issue]  Lots of errors pop up

### ISSUE THREAD

**Issue by wherear3y0** [Voltstro-Studios/UnityWebBrowser#158]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.8f1

### Describe what the issue you are experiencing is.

Good afternoon, when I installed your plugin according to the instructions from the github, errors like these pop up

and also, to be honest, I can’t figure out how to import the browser into the project itself

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(33,17): error CS0246: The type or namespace name 'Keyboard' could not be found (are you missing a using directive or an assembly reference?)`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(11,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(12,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputHelper.cs(156,59): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?)
`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(23,41): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(27,45): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)`
`Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.1\Runtime\Input\WebBrowserInputSystemHandler.cs(33,17): error CS0246: The type or namespace name 'Keyboard' could not be found (are you missing a using directive or an assembly reference?)`
![Снимок экрана 2023-04-04 203232](https://user-images.githubusercontent.com/104694707/229872102-2574d31c-dd0e-450e-88a2-8ca99fc6d275.png)

**Comment by wherear3y0** [comment]
I fixed it with this article - https://stackoverflow.com/questions/63636944/unity-type-or-namespace-name-inputsystem-does-not-exist-in-the-namespace-unit

But now a new problem appears and I also can't figure out how to display the browser in the project - the rectangle to which I added the Web Browser and configured it does nothing

**Comment by wherear3y0** [comment]
![image](https://user-images.githubusercontent.com/104694707/229877895-805938e9-affe-479b-a60c-15cfadf43f75.png)

**Comment by Voltstro** [comment]
Try seeing if the sample works. [See here for how to do that](https://projects.voltstro.dev/UnityWebBrowser/articles/user/usage/#samples).

The last error you provided doesn't really say much.

**Comment by wherear3y0** [comment]
I don't have samples in Package Manager(

**Comment by Voltstro** [comment]
Do samples for other packages (any packages, such as the Input System package) show up? If not then there is some other issue with your Unity.

**Comment by Voltstro** [comment]
No response, assuming all is good now. If not, please respond and open the issue again thank you.
