### ISSUE TITLE
[Issue] A get random errors

### ISSUE THREAD

**Issue by dmandic-htec** [Voltstro-Studios/UnityWebBrowser#161]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.11f1

### Describe what the issue you are experiencing is.

I get random errors when I run my Unity application using UWB. Sometimes it's works fine all day, and the next day I can't run it because it said that UWB can't be started or it can't open same URL that I'm using from the start.

### Provide reproducible steps for this issue.

1. Run my application from Unity Editor or build a solution and run it.

### Any additional info you like to provide?

![error1](https://user-images.githubusercontent.com/86605939/234908743-072e6c7d-76d2-4acd-bdb9-690346af7560.PNG)
![error2](https://user-images.githubusercontent.com/86605939/234908766-126beec5-00ee-4554-9226-41d6e495c564.PNG)

**Comment by Voltstro** [comment]
Probably similar issue is happening in #153. I have yet been able to reproduce any of these issues, so ideally I need a sample project, or reproducible setup steps.

Please response in the issue provided before, to help stop duplicate issues.
