### ISSUE TITLE
[Issue] How to input Chinese?

### ISSUE THREAD

**Issue by zhangzuojing** [Voltstro-Studios/UnityWebBrowser#162]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Github Master Branch

### What Unity version are you running?

2021.3.6

### Describe what the issue you are experiencing is.

I have to say thanks the developers first.It is really a wonderful and useful plugin for unity . 

Then I tried to use it , than there is the problem that  I CANNOT input chinese in web tables . And I think it is also happened when I try to input other characters such as Japanese or other language need IME.

So please tell me how to fix that in source code？Thx！

### Provide reproducible steps for this issue.

1. Click the web input label in web
2. Open IME and try to input Chinese.
3. Can't see the cursor and Can't input Chinese

**Comment by zhangzuojing** [comment]
Thx for the advice，I will try that

**Comment by Voltstro** [comment]
Initial IME support will be in the latest version. Main issue I know of right now is that the IME window has some positional issues, but that be fixed later.
