### ISSUE TITLE
[Issue] How to open multiple different web pages at the same time in unity

### ISSUE THREAD

**Issue by dtzlop** [Voltstro-Studios/UnityWebBrowser#163]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.23

### Describe what the issue you are experiencing is.

How to open multiple different web pages at the same time in unity。
I tried to copy the new ENGINE and new Tcp, but it didn't work, an error was reported

### Provide reproducible steps for this issue.

Open 2 BrowserControllers at the same time

### Any additional info you like to provide?

![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/75352475/42e1b2c4-0575-49ab-b5fd-3db571fc0573)

**Comment by Voltstro** [comment]
I myself had no issues running two instances of UWB. I created two copies of the browser controller, then created a separate TCP communication layer asset with different ports set.

Both instances running:
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/5a9fdbc4-1a2e-4253-8a38-7d228b180050)

The new TCP Communication layer asset was created via the context menu, like so:
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/ba34c064-01c0-418a-b26f-de4c566752c4)

Here is the new TCP Communication layer asset, I changed the ports to 6555 and 6556.
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/c1cd4822-6c1b-461b-8aec-d0a5b9ddf70d)

This is the default TCP Communication layer asset provided by the Unity Web Browser package, I did not alter the ports (default 5555 and 5556).
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/7aa726e9-f332-4159-a3f3-2cb569563bec)
