### ISSUE TITLE
[Issue Tracker] "The engine did not get ready within engine startup timeout!"

### ISSUE THREAD

**Issue by Voltstro** [Voltstro-Studios/UnityWebBrowser#166]
#  Tracker

We are using this issue to track this error: "The engine did not get ready within engine startup timeout!".

## Issue

We have been getting a lot of reports of UWB not starting, and spitting the above error message out. We've yet to reproduce this issue on our end, so we are creating this issue to track all reports of the error.

## Report

If you are having this issue, try these steps first:

1. Make sure you are using the latest version of UWB
2. Increase 'Engine Startup Timeout`.
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/64cb6069-5720-4e4a-9c52-080fcbc32c24)
3. Delete Unity's `Library` Folder
4. Disable UWB's cache

If you have tried these steps, then move onto providing us an issue report HERE (in the comments on this issue).

Start by getting the error message:

1. First, increase logging level to Debug.
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/6b3fbeef-01ae-4b65-a335-d4350d3d89ad)
2. Run your project, get the error.

Once you have the error, provide these details in a comment on this issue:

- Provide us ALL log messages in the console for this session where the error occurred. DO NOT JUST PROVIDE A PICTURE OF YOUR CONSOLE, provide it in text format with the stack traces, and put everything in [GitHub's markdown code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) so it is easy to read. If you want an easy way to copy it, go to your [Unity editor log file](https://docs.unity3d.com/Manual/LogFiles.html), and copy the text for the error's session from there.

- There is a second log file created at `Library/UnityWebBrowser.Engine.Cef.log`. Please also attach this log file.

- What Platform (OS) you are using, and your Unity editor version.

**Comment by shubhamnegi1234** [comment]
[UnityWebBrowser.Engine.Cef.log](https://github.com/Voltstro-Studios/UnityWebBrowser/files/12214426/UnityWebBrowser.Engine.Cef.log)

Error 1 - [Web Browser]: The engine did not get ready within engine startup timeout! Try increasing your 'Engine Startup Timeout' time. If you continue to have this error, see issue report #166 on GitHub.
UnityEngine.Logger:LogError (string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__57:MoveNext () (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Core/WebBrowserClient.cs:415)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__57>:Run () (at 
 
Warning  - [Web Browser]: [Engine]: No communication layer provided, using default TCP...
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Logging.ProcessLogHandler:HandleOutputProcessLog (object,System.Diagnostics.DataReceivedEventArgs) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/ProcessLogHandler.cs:50)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback () 

I DONT KNOW WHY IS IT GIVING THIS WARNING BEACAUSE tcp FILE IS ATTACHED ON SCRIPT AND ( THERE ARE TWO WAY TO FIX IT ONE TO CLEAR CACHE ON TASK MANAGER AND SOMETIMES IT DOES NOT SHOW UP IN THERE SOI CHANGE THE tcp PORT AND IT WORKS FOR FOR FEW MINUTES )


KINDLY HELP ME OUT WITH THIS

**Comment by Voltstro** [comment]
Looking at the CEF logs, it appears the cache is still locked by an another UWB process, meaning that the CEF process is not shutting down correctly for some reason...

Try disabling the cache in Client settings.
![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/cb04164b-4213-48e2-b418-cc07788b0ca5)



> Warning - [Web Browser]: [Engine]: No communication layer provided, using default TCP...

If your communication layer is set to TCP, then this debug log message is expected.

**Comment by shubhamnegi1234** [comment]
I tried disabling the cache as well but still having the same issue, 
and yes the communication layer is set to TCP, should I change it?

**Comment by yonixw** [comment]
I changed it to 60000 (60 sec) and it worked... so maybe just more time is needed with late version of CEF

**Comment by OdCheban** [comment]
I have the same problem, restarting the computer helps. Is there another solution to the problem?

**Comment by RMichaelPickering** [comment]
I set the timeout to much longer and this seems to have resolved the issue. CEF is perhaps a bit of a resource hog which probably explains why it takes a bit long to start! Given this, it may make sense to increase the default startup timeout.

**Comment by nitroman123** [comment]
another start error [Web Browser]: [Engine]: Error setting up IPC!
VoltRpc.Versioning.VersionMissMatchException: Version miss-match! Host excepting version 3.2.0
   at VoltRpc.Communication.Client.InvokeSyncCheck()
   at VoltRpc.Communication.Client.Initialize(BufferedReader , BufferedWriter )
   at VoltRpc.Communication.Client.Initialize(Stream , Stream )
   at VoltRpc.Communication.TCP.TCPClient.Connect()
   at VoltstroStudios.UnityWebBrowser.Engine.Shared.Core.EngineEntryPoint.SetupIpc(IEngineControls engineControls, LaunchArguments arguments)
UnityEngine.Logger:LogError (string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36)
VoltstroStudios.UnityWebBrowser.Logging.ProcessLogHandler:HandleOutputProcessLog (object,System.Diagnostics.DataReceivedEventArgs) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/ProcessLogHandler.cs:54)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by Voltstro** [comment]
> another start error [Web Browser]: [Engine]: Error setting up IPC! VoltRpc.Versioning.VersionMissMatchException: Version miss-match! Host excepting version 3.2.0 at VoltRpc.Communication.Client.InvokeSyncCheck() at VoltRpc.Communication.Client.Initialize(BufferedReader , BufferedWriter ) at VoltRpc.Communication.Client.Initialize(Stream , Stream ) at VoltRpc.Communication.TCP.TCPClient.Connect() at VoltstroStudios.UnityWebBrowser.Engine.Shared.Core.EngineEntryPoint.SetupIpc(IEngineControls engineControls, LaunchArguments arguments) UnityEngine.Logger:LogError (string,object) VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36) VoltstroStudios.UnityWebBrowser.Logging.ProcessLogHandler:HandleOutputProcessLog (object,System.Diagnostics.DataReceivedEventArgs) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Logging/ProcessLogHandler.cs:54) System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

This error has nothing to do with this issue.

**Comment by jacobbullock** [comment]
I am getting this error: 

```
[Web Browser]: The engine did not get ready within engine startup timeout! Try increasing your 'Engine Startup Timeout' time. If you continue to have this error, see issue report #166 on GitHub.
UnityEngine.Logger:LogError (string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__58:MoveNext () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:439)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__58>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:210)
Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskExtensions.cs:409)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.ValueTuple`3<int, bool, bool>>:TrySetResult (System.ValueTuple`3<int, bool, bool>) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>:TryInvokeContinuationT2 (Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>,Cysharp.Threading.Tasks.UniTask`1/Awaiter<bool>&) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.WhenAny.Generated.cs:99)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2/<>c<bool, bool>:<.ctor>b__2_1 (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.WhenAny.Generated.cs:58)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayPromise:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.Delay.cs:763)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:104)
```

I disabled the cache and set my timeout to `30000`

Other Logs:

```
[Web Browser]: Arguments: '-initial-url "https://voltstro.dev" -width 1920 -height 1038 -javascript True -background-color FFFFFFFF -log-path "C:\Users\jacob\work\magic-sdk\source\magic-unity-demo\MagicUnityTemplate\Library\UnityWebBrowser.Engine.Cef.log" -log-severity Debug -in-location "5555" -out-location "5556" -popup-action "Ignore" -local-storage True -proxy-server False'
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Helper.WebBrowserUtils:CreateEngineProcess (VoltstroStudios.UnityWebBrowser.Logging.IWebBrowserLogger,VoltstroStudios.UnityWebBrowser.Core.Engines.Engine,string,System.Diagnostics.DataReceivedEventHandler,System.Diagnostics.DataReceivedEventHandler) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Helper/WebBrowserUtils.cs:187)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:StartEngineProcess (string) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:413)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<>c__DisplayClass56_0:<Init>b__0 () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:401)
Cysharp.Threading.Tasks.UniTask:Create (System.Func`1<Cysharp.Threading.Tasks.UniTask>) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.Factory.cs:81)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:Init () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:400)
VoltstroStudios.UnityWebBrowser.Core.BaseUwbClientManager:Start () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/BaseUwbClientManager.cs:32)
```

```
[Web Browser]: Logger initialized at "08/03/2024 12:03 PM"
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Logging.ProcessLogHandler:HandleOutputProcessLog (object,System.Diagnostics.DataReceivedEventArgs) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/ProcessLogHandler.cs:50)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

```
[Web Browser]: [Engine]: No communication layer provided, using default TCP...
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Logging.ProcessLogHandler:HandleOutputProcessLog (object,System.Diagnostics.DataReceivedEventArgs) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/ProcessLogHandler.cs:50)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```


```
[Web Browser]: UWB shutdown...
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Debug (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:26)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:ReleaseResources () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:1065)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:Dispose () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:1055)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__58:MoveNext () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.1.0/Runtime/Core/WebBrowserClient.cs:444)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__58>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:210)
Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskExtensions.cs:409)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.ValueTuple`3<int, bool, bool>>:TrySetResult (System.ValueTuple`3<int, bool, bool>) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>:TryInvokeContinuationT2 (Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>,Cysharp.Threading.Tasks.UniTask`1/Awaiter<bool>&) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.WhenAny.Generated.cs:99)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2/<>c<bool, bool>:<.ctor>b__2_1 (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.WhenAny.Generated.cs:58)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayPromise:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/UniTask.Delay.cs:763)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.3/Runtime/Internal/PlayerLoopRunner.cs:104)
```

**Comment by jamesrp13** [comment]
@Voltstro everyone on my team has encountered the issue @jacobbullock is having. Seeing as it’s a blocker to what we’re doing we’re very motivated to figure it out. Is there something else we can provide to be helpful here? Maybe jump on a call so you can see what we’re encountering live?

**Comment by RMichaelPickering** [comment]
Just to add a further follow up, the issue is still occurring on a somewhat regular basis, even after trying all the suggestions (including mine). By the way, if anything this issue seems to be worse after updating to the latest release. I'd further add that disabling the cache is a poor solution at best, as it tends to push responsiveness from barely acceptable to simply awful!
@Voltstro Can you please share more information about your repro attempts, in particular, have you tested on Windows, without local storage, and with or without cache? Also, for me this is a BIG problem when running a built project on Windows (both 10 and 11), where the issue seems to occur sometimes even on first starting the build, although somewhat randomly.

**Comment by RMichaelPickering** [comment]
I think I finally, really, figured this out! The issue is caused by "Graphics APIs for Windows" set to "Direct3D12" in "Player" settings. I've set to only "Direct3D11" which is now working well!

**Comment by jacobbullock** [comment]
I updated to use Direct3D11 today and that didn't seem to fix it for me. I am noticing something very strange though.  If I restart my laptop, I am able to open unity and work on the app and have the browser work without any issue for what seems like 25-30 minutes.  Making some code changes, running the app, over and over.  After about 30 minutes the browser stops working.  I've tried quitting just unity and that doesn't seem to fix it. I have to restart my whole computer and I can work with the browser again.  Is it possible there is something being left behind in memory when quitting the app and rebuilding?

**Comment by Voltstro** [comment]
I've been taking a look into this. I think I have reproducible steps now.

1. Start UWB with cache turned on
2. Force Unity to close or do a domain reload
3. Start UWB again with cache disabled, get error after timeout

From here, you can see that the UWB Engine process is still running in the background, with the ports bounded. Normally UWB will send a shutdown signal to the engine process, and even if it doesn't shutdown in time, UWB will force kill it. But with either a domain reload or a force close, UWB doesn't get a chance to do that.

---

I really see three issues that need be fixed here.

- Since the engine's start listening method is async, the exception related to the port already been bound is getting swallowed.
- The engine process is allowed to linger when the main Unity process closes and the Unity process doesn't get a chance to tell the Engine process to shutdown 
- Need to either shutdown UWB on Unity domain reload, or prevent Unity from domain reloading when UWB is running.

**Comment by Voltstro** [comment]
Release 2.1.1 includes fixes to potentially resolve this issue.

Please update and see if you can get the issue to occur. (Ensure that no UWB Engine process is running in the background)

**Comment by RMichaelPickering** [comment]
I've now implemented the latest release and confirm that it works and seems more stable than the previous release. In preliminary testing I found no issues with any UWB engine processes lingering. I have not yet completed extensive testing for the original issue but have not encountered the timeout error so far!

**Comment by jacobbullock** [comment]
We have not seen the engine timeout issue at all with `2.1.1`.

**Comment by Voltstro** [comment]
No one has reported this issue in three months. Closing as completed.

**Comment by AP2020C** [comment]
Premise that last week was working perfectly

Log:
```
[468:17596:1004/195205.727:WARNING:chrome_main_delegate.cc(745)] This is Chrome version 128.0.6613.120 (not a warning)
[468:17596:1004/195206.517:WARNING:chrome_command_line_pref_store.cc(121)] Additional command-line proxy switches specified when --no-proxy-server was also specified.
[468:17596:1004/195206.911:WARNING:chrome_command_line_pref_store.cc(121)] Additional command-line proxy switches specified when --no-proxy-server was also specified.
```
Error:
```
[UWB]: The engine did not get ready within engine startup timeout! Try increasing your 'Engine Startup Timeout' time. If you continue to have this error, see issue report #166 on GitHub.
UnityEngine.Logger:LogError (string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.0/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__63:MoveNext () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.0/Runtime/Core/WebBrowserClient.cs:454)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient/<WaitForEngineReadyTask>d__63>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/CompilerServices/StateMachineRunner.cs:210)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:59)
Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTaskExtensions.cs:410)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<Cysharp.Threading.Tasks.UniTaskExtensions/<Timeout>d__12>:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.ValueTuple`3<int, bool, bool>>:TrySetResult (System.ValueTuple`3<int, bool, bool>) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>:TryInvokeContinuationT2 (Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2<bool, bool>,Cysharp.Threading.Tasks.UniTask`1/Awaiter<bool>&) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTask.WhenAny.Generated.cs:99)
Cysharp.Threading.Tasks.UniTask/WhenAnyPromise`2/<>c<bool, bool>:<.ctor>b__2_1 (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTask.WhenAny.Generated.cs:58)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayPromise:MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/UniTask.Delay.cs:790)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at ./Library/PackageCache/com.cysharp.unitask@2.5.5/Runtime/Internal/PlayerLoopRunner.cs:104)
```

**Comment by lanceroller** [comment]
<img width="1240" height="43" alt="Image" src="https://github.com/user-attachments/assets/d9a6445e-4cf9-47a4-8130-6a555181ea8b" />

<img width="344" height="28" alt="Image" src="https://github.com/user-attachments/assets/f43e6322-d26f-4301-a954-85e2d76dd7bc" />

<img width="308" height="100" alt="Image" src="https://github.com/user-attachments/assets/f1c21a7b-a087-4891-9a5b-870de9f7c873" />


Will I have to upgrade my Ubuntu in order to use the newest UWB packages? Seems like it may not run with older versions of Glibc?
