### ISSUE TITLE
[Issue] IL2CPP

### ISSUE THREAD

**Issue by asimsenyuva** [Voltstro-Studios/UnityWebBrowser#169]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.5.f1

### Describe what the issue you are experiencing is.

- Scrool Bars not woring with mouse but scrool whell working.
- Mono backed build works but **IL2CPP** build not work

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

**Comment by Voltstro** [comment]
Like stated in the docs, UWB does not support IL2CPP. I currently don't have any plans to work on adding support for IL2CPP.
