### ISSUE TITLE
Live video web page

### ISSUE THREAD

**Issue by Keep-curiosity** [Voltstro-Studios/UnityWebBrowser#17]
Thanks for your project.I hava a issues. Can run youtube live video  web page?
I can not open this project. What should I do? 
![7b948b3f2961849bc1bf0cbd59ae0c8](https://user-images.githubusercontent.com/26104385/132055732-b85fded3-0876-48ab-a845-4dde1f77237b.png)

**Comment by Voltstro** [comment]
From what I can tell, you didn't clone the repository recursively. 
You need to clone it with `git clone --recursive https://github.com/Voltstro-Studios/UnityWebBrowser.git`. (Or just initialize the submodules with `git submodule init` and `git submodule update`.)

**Comment by Keep-curiosity** [comment]
Thank you my friend, it's working
