### ISSUE TITLE
I want to use uwb at multiple screen , but only one is working the rest copies are giving communication error , please help me out with it.

### ISSUE THREAD

**Issue by shubhamnegi1234** [Voltstro-Studios/UnityWebBrowser#174]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.21f1

### Describe what the issue you are experiencing is.

InitializationException: The communication layer is already in use! 

This error i am getting while using the multiple uwb.

### Provide reproducible steps for this issue.

1. Drag prefeb of uwb on scene 
2. made copies 
3. Hit play to check , it gave above error.

### Any additional info you like to provide?

I want to use it multiple places 
![errors](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/134511004/c49a4888-285f-4757-8f69-19a527c0ea1f)

**Comment by Voltstro** [comment]
Duplicate #163.

**Comment by shubhamnegi1234** [comment]
Thank you @Voltstro  you guys are Rockstars
