### ISSUE TITLE
The web browser not working on WEBGL 2.0 in unity  

### ISSUE THREAD

**Issue by shubhamnegi1234** [Voltstro-Studios/UnityWebBrowser#200]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.21f1

### Describe what the issue you are experiencing is.

The web browser is working on the editor but while creating webGL build it gives an error.

ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
VoltstroStudios.UnityWebBrowser.Editor.EditorHelper.UnityBuildTargetToPlatform (UnityEditor.BuildTarget buildTarget) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Editor/EditorHelper.cs:43)
VoltstroStudios.UnityWebBrowser.Editor.EngineManagement.EngineManagerPostprocess.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/dev.voltstro.unitywebbrowser@2.0.2/Runtime/Editor/EngineManagement/EngineManagerPostprocess.cs:30)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass18_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at <57a8ad0d1492436d8cfee9ba8e6618f8>:0)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at <57a8ad0d1492436d8cfee9ba8e6618f8>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

### Any additional info you like to provide?

Also but in another system the build was created but still the web browser was not working.

**Comment by Voltstro** [comment]
WebGL is not supported by UWB.

**Comment by shubhamnegi1234** [comment]
what platforms does it supports?
