### ISSUE TITLE
I'm using UWB to play html5 file with embedded video (video in local folder) but it doesn't work. It shows error "[Web Browser]: [CEF Engine Console]: Uncaught (in promise) NotSupportedError: The element has no supported sources.". I tried different ways: open html5 as file, open via localhost/remote host but it didn't work. It only worked with embedded video from youtube.

### ISSUE THREAD

**Issue by longkakavn** [Voltstro-Studios/UnityWebBrowser#246]
I'm using UWB to play html5 file with embedded video (video in local folder) but it doesn't work. It shows error "[Web Browser]: [CEF Engine Console]: Uncaught (in promise) NotSupportedError: The element has no supported sources.". I tried different ways: open html5 as file, open via localhost/remote host but it didn't work. It only worked with embedded video from youtube.
Anyone knows how to fix this, please?
Thanks in advanced!

_Originally posted by @longkakavn in https://github.com/Voltstro-Studios/UnityWebBrowser/discussions/245_

**Comment by Voltstro** [comment]
Don't open an issue for a question or discussion.
