### ISSUE TITLE
Sample Project Broken cant make the setup... 

### ISSUE THREAD

**Issue by nitroman123** [Voltstro-Studios/UnityWebBrowser#278]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.16

### Describe what the issue you are experiencing is.

trying from yesterday and everything broken with missing packages i don't know why...  Sample project that "should be ok" its not...  
Also doesn't tell you what else you need... Maybe an auto packages resolver cause this is a mess 

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

**Comment by nitroman123** [comment]
another error Library\PackageCache\dev.voltstro.unitywebbrowser@2.0.2\Runtime\Core\PixelsEventTypeReader.cs(47,46): error CS0121: The call is ambiguous between the following methods or properties: 'VoltRpc.Extension.Memory.BufferedReaderMemoryExtensions.ReadBytesSpanSlice(VoltRpc.IO.BufferedReader, int)' and 'VoltRpc.IO.BufferedReaderExtensions.ReadBytesSpanSlice(VoltRpc.IO.BufferedReader, int)'

**Comment by M0rph3v5** [comment]
also getting a lot of errors opening the sample project from within the repo

```/Users/bonjo/Downloads/UnityWebBrowser-master/src/Packages/UnityWebBrowser.Communication.Pipes/Runtime/Base/EnginePipesCommunicationLayer.cs(7,39): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'VoltstroStudios.UnityWebBrowser' (are you missing an assembly reference?)
``` 

being one example

**Comment by nitroman123** [comment]
dont know but its totally broken and instructions is a mess

**Comment by Voltstro** [comment]
> also getting a lot of errors opening the sample project from within the repo
> 
> /Users/bonjo/Downloads/UnityWebBrowser-master/src/Packages/UnityWebBrowser.Communication.Pipes/Runtime/Base/EnginePipesCommunicationLayer.cs(7,39): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'VoltstroStudios.UnityWebBrowser' (are you missing an assembly reference?)
> 
> being one example

@M0rph3v5 

You haven't not read the setup dev setup instructions if you are getting this error using the repo. Also please keep different issues in separate issues.

**Comment by Voltstro** [comment]
No response in over a month, closing.
