### ISSUE TITLE
[Issue] UnityWebBrowser package not found when adding the scoped registries

### ISSUE THREAD

**Issue by M0rph3v5** [Voltstro-Studios/UnityWebBrowser#279]
### What platform are you experiencing this issue on?

MacOS

### What architecture is your platform?

Other

### What version of UWB are you using?

Github Master Branch

### What Unity version are you running?

2022.3.18f1

### Describe what the issue you are experiencing is.

![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/598604/b05656af-2e93-458b-b40a-fcc2e2a15a33)

inserted all packages from documentation, unitywebbrowser package is not visible, not when searched, added by name or anything.

### Provide reproducible steps for this issue.

1. I added the scoped registrys
2. Looked for webbrowser package
3. Did not find it

**Comment by Voltstro** [comment]
You say 'Github Master Branch' as your version, so you are using the local UWB dev project? But then you say the UWB is not appearing in the list, which is not possible using that project. So I'll assume your using VoltstroUPM. I don't know why its not appearing, but you can add it manually by clicking the plus icon, then 'add by name', then type`dev.voltstro.unitywebbrowser`.

Also we don't support MacOS.

**Comment by M0rph3v5** [comment]
ah yeah my bad. I'm using the VolstroUPM. 

I tried adding by name which results into an error.

**Comment by M0rph3v5** [comment]
I'll check if I can get it to work on windows

**Comment by Voltstro** [comment]
Hmm odd. Looks like you might of not setup VoltstroUPM correctly.

If you open your project's `Packages/manifest.json` file, it should look like this:

```json
{
  "dependencies": {
    ...
    "dev.voltstro.unitywebbrowser": "2.0.2",
    "dev.voltstro.unitywebbrowser.engine.cef": "2.0.2-113.3.1",
    "dev.voltstro.unitywebbrowser.engine.cef.win.x64": "2.0.2-113.3.1",
    ...
  },
  "scopedRegistries": [
    {
      "name": "Voltstro UPM",
      "url": "https://upm-pkgs.voltstro.dev",
      "scopes": [
        "org.nuget",
        "dev.voltstro",
        "com.cysharp.unitask"
      ]
    }
  ]
}

```

**Comment by Voltstro** [comment]
No response in over a month, closing.
