### ISSUE TITLE
[Issue] Webview stops working after a certain time without being used

### ISSUE THREAD

**Issue by Quentin-Tran** [Voltstro-Studios/UnityWebBrowser#300]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.15f1

### Describe what the issue you are experiencing is.

It seems webviews stop working if you don't use them for a while. Maybe a time out if we stop using the web engine ?

### Provide reproducible steps for this issue.

1. Create a new empty project.
2. Import Unity Web Browser Basic samples and drag and drop _UnityWebBrowser_ prefab into the scene.
3. Play
4. Wait for 10 minutes without using the webview (I don't know if the bug can be trigger quicker :/ )
5. Focus the search field, enter a random url and click on the button to start searching.
6. It doesn't work, I got this errors logs : 
```
[Web Browser]: [Engine]: Uncaught exception occured in the entry point!
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host computer
```

**Comment by Voltstro** [comment]
Release 2.2.0 has been released that increases default timeout to max. Should basically solve this issue.
