### ISSUE TITLE
[Issue] Dropdown not active

### ISSUE THREAD

**Issue by bloedrivier** [Voltstro-Studios/UnityWebBrowser#314]
### What platform are you experiencing this issue on?

Linux

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2022.3.26f1

### Describe what the issue you are experiencing is.

![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/110369371/26bf55cc-f520-474e-b378-32c821805bdc)

This dropdown does not drop down...

If I click on it, I can change the domain using the `arrow keys` and `shift+2`.

![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/110369371/78a01892-31dd-4283-9561-7c499b29a30e)

### Provide reproducible steps for this issue.

1. I did this.
2. I then did that.
3. Boom! Issue.

**Comment by Voltstro** [comment]
Issue was with HTML `select` elements. CEF requires a custom implementation in off-screen-rendering mode for these elements.

I have done the required implementation, all seems to be working now.

![image](https://github.com/Voltstro-Studios/UnityWebBrowser/assets/45032877/96b5238e-8c84-4137-85b3-7201c17daca7)

I will leave the issue open until this fix has been released.

**Comment by Voltstro** [comment]
Release 2.2.0 has been released with this fix.
