### ISSUE TITLE
[Issue] Keyboard Inputs do not work in web games

### ISSUE THREAD

**Issue by splamei** [Voltstro-Studios/UnityWebBrowser#335]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2022.3.33

### Describe what the issue you are experiencing is.

I'm making a custom client for a web based game. However, I have found out that keyboard inputs in the game don't work (and the Google Login page is broken). This mean I won't be able to make the client. I don't know if it's something that can't be fixed or something I need to do.

### Provide reproducible steps for this issue.

1. Simple play a map in Rhythm Plus

**Comment by Voltstro** [comment]
Google Login does not work since Google blocks login requests from CEF.

---

Keyboard issue seems to be because keyboard events in JS are not firing due to incorrect implementation of key handling in UWB. This will need to be fixed.

**Comment by splamei** [comment]
When I mean Google Login doesn't work, I mean selecting the email input box does nothing.

**Comment by splamei** [comment]
That's what I meant. I should of been more specific sorry

**Comment by Voltstro** [comment]
Release 2.2.0 has been released with fix for keyboard events not working.

**Comment by splamei** [comment]
Ok! Thank you for the fix
