### ISSUE TITLE
[Issue] Problem With Disposing/Destroying A WebClient When There Are Multiple Instances

### ISSUE THREAD

**Issue by JAng-A3** [Voltstro-Studios/UnityWebBrowser#358]
### What platform are you experiencing this issue on?

Windows x64

### What version of UWB are you using?

2.2.1

### What Unity version are you running?

2023.2.12f

### Describe what the issue you are experiencing is.

I am currently working on a program that requires the instantiating and deleting of multiple webpage instances, and it's currently working as intended when enabling the webpages (the webpage and canvas are prefabs that are instantiated and fed a dynamically created CommunicationLayer with unique in and out ports, though they use the same engine configuration and input handler)

Disabling/deleting it using code also works well for a single instance (triggering the WebBrowserClient's Dispose function before deleting the WebBrowserClient and canvas GameObject)

However, when there are two or more instances of the webpage, deleting one of them will trigger the following errors:

**[UWB]: Error in data loop! System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.**

**[UWB]: It appears that the engine process has quit!**

And I am unable to interact with the remaining instances as they give me this error:

**[UWB]: An error occured while executing task SendMouseMoveEvent! System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.**

### Provide reproducible steps for this issue.

1. Make the Canvas with a WebBrowserBasic game object attached to it as a prefab
2. Instantiate 2 or more of the prefabs through code, giving them a dynamically created TCP Communication layer with a unique in/out port and assigning the initial URL
3. Trigger the WebBrowserClient.Dispose function of one of the instances before destroying the Canvas game object
4. Hover mouse over remaining WebBrowserBasic instances

**Comment by Voltstro** [comment]
This has been fixed in release 2.2.4.
