### ISSUE TITLE
[Issue]: WebBrowserClient does not contain a definition for 'LogWarning' 

### ISSUE THREAD

**Issue by ThatBulgarian** [Voltstro-Studios/UnityWebBrowser#46]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Stable (1.6.3) GitLab Package

### What Unity version are you running?

2021.2.12f1

### Describe what the issue you are experiencing is.

![image](https://user-images.githubusercontent.com/4185659/155565622-b4bfc331-f073-4c3c-8b4b-6cecf58bdbc2.png)

### Provide reproducible steps for this issue.

1. Open existing unity project
2. Add packages as instructed on repo home page
3. Error shows after downloading packages

**Comment by Voltstro** [comment]
Someone on Discord had this issue as well, it seems to be that Unity sometimes doesn't download git packages correctly, so just re-install the packages, and that should fix it.

Also side note, that version you are installing is 2.0-preview, not 1.6.3 stable. But I would recommend staying with 2.0-preview.
