### ISSUE TITLE
[Issue]: Readme "Operating System Support" doesn't mention Android

### ISSUE THREAD

**Issue by andybak** [Voltstro-Studios/UnityWebBrowser#75]
### What platform are you experiencing this issue on?

Other

### What architecture is your platform?

Other

### What version of UWB are you using?

Git Repo

### What Unity version are you running?

n/a

### Describe what the issue you are experiencing is.

Operating System Support doesn't mention Android. That might either mean "It's just Linux, dummy" or "Sorry, nope!" but it would be nice to be explicit either way.

### Provide reproducible steps for this issue.

1. I read the readme
2. I was none the wiser as to whether Android was supported
3. I really hate Issue reporting that doesn't allow me to just type something simple when appropriate ;-)

**Comment by Voltstro** [comment]
No, it only supports desktop platforms. I'll update the readme to reflect this.

> I really hate Issue reporting that doesn't allow me to just type something simple when appropriate ;-)

We use discussions for basic question like this, its why we have it setup like this.

**Comment by andybak** [comment]
> We use discussions for basic question like this, its why we have it setup like this.

Ah. Sorry. I never even think to look for "Discussions" - I'm so used to using Issues. Bad habit I'll try and break.
