### ISSUE TITLE
have some doubts

### ISSUE THREAD

**Issue by wzxinchen** [Voltstro-Studios/UnityWebBrowser#82]
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Preview GitLab Package

### What Unity version are you running?

2021.3.2

### Describe what the issue you are experiencing is.

1. When the mouse enters the webpage, there is no deformation, especially when entering the text box, there is no deformation
2. The scroll bar of dragging the web page is invalid, but the scroll bar is normal when sliding the wheel inside the web page
3. There is a slight blur, others are normal

I don't know if I'm missing something, or if it's true

### Provide reproducible steps for this issue.

1. Just open www.baidu.com

### Any additional info you like to provide?

no

**Comment by Voltstro** [comment]
> When the mouse enters the webpage, there is no deformation, especially when entering the text box, there is no deformation

I am not too sure what you mean by this. Are you saying how the cursor doesn't change to a text select cursor?

> The scroll bar of dragging the web page is invalid, but the scroll bar is normal when sliding the wheel inside the web page

Yep, I am aware of the scrolling issue when you try to drag it using the mouse.

> There is a slight blur, others are normal

I don't see any blurriness when UWB is displaying baidu. Screenshots would be nice to provide.

**Comment by Voltstro** [comment]
Closing due to no response. Feel free to open again if you (or someone) provides a response.
